(function(g){var window=this;'use strict';var ygb=function(a){g.T.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.Tf=!1;this.player=a;this.S(a,"onStateChange",this.SO);this.S(a,"videodatachange",this.vp);this.S(a,"onInlinePreviewModeChange",this.x3);this.kf=new g.no(this.yv,null,this);g.D(this,this.kf)},b6=function(a){g.iS.call(this,a);
this.j=new ygb(this.player);g.D(this,this.j);this.j.hide();g.dR(this.player,this.j.element,4);if(a.isInline()){this.load();var b=a.getRootNode();g.yo(b,["ytp-inline-preview-mode","ytp-no-contextmenu"]);this.player.T().K("web_inline_player_disable_scrubbing")&&g.Bo(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0)}};
g.v(ygb,g.T);g.k=ygb.prototype;
g.k.YL=function(){this.tooltip=new g.IV(this.player,this);g.D(this,this.tooltip);g.dR(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Qc=new g.aT(this.player);g.D(this,this.Qc);this.Uj=new g.T({G:"div",Ia:["ytp-inline-preview-scrim"]});g.D(this,this.Uj);this.Uj.Da(this.element);this.S(this.Uj.element,"click",this.NG);this.sj=new g.BV(this.player,this,300);g.D(this,this.sj);this.sj.Da(this.Uj.element);this.controls=new g.T({G:"div",N:"ytp-inline-preview-controls"});g.D(this,this.controls);
this.controls.Da(this.element);var a=new g.HU(this.player,this,this.player.T().K("kevlar_simp_remove_min_width_for_mute_button"));g.D(this,a);a.Da(this.controls.element);a=new g.zV(this.player,this);g.D(this,a);a.Da(this.controls.element);this.Jc=new g.OU(this.player,this);g.D(this,this.Jc);g.dR(this.player,this.Jc.element,4);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){g.oo(this.kf);this.Tf||(this.YL(),this.Tf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show()};
g.k.hide=function(){this.kf.stop();g.T.prototype.hide.call(this);this.player.isInline()||this.Tf&&this.Jc.hide()};
g.k.ra=function(){g.T.prototype.ra.call(this)};
g.k.NG=function(a){a.target===this.Uj.element&&this.player.Na("onExpandInlinePreview",a)};
g.k.x3=function(){g.Bo(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ie=function(){this.Jc.xc();this.sj.xc()};
g.k.yv=function(){this.Ie();g.oo(this.kf)};
g.k.Eb=function(){g.aV(this.Jc,0,this.player.gb().getPlayerSize().width,!1);g.PU(this.Jc)};
g.k.SO=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.vp=function(a,b){if(this.player.isInline()){g.Bo(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.FI);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Bo(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Dc=function(){return this.tooltip};
g.k.jg=function(){return!1};
g.k.ih=function(){return!1};
g.k.Qb=function(){return!1};
g.k.Il=function(){return!1};
g.k.ED=function(){};
g.k.Np=function(){};
g.k.Tx=function(){};
g.k.Gm=function(){return null};
g.k.BF=function(){return null};
g.k.EF=function(){return new g.je(0,0)};
g.k.LB=function(){return null};
g.k.xk=function(){return new g.Fl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Kv=function(a,b,c,d,e){var f=d=0,h=0,l=g.Zl(a);if(b){c=g.wo(b,"ytp-mute-button");var m=g.wo(b,"ytp-subtitles-button"),n=g.Xl(b,this.element);b=g.Zl(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.gb().getPlayerSize().width;h=g.be(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.mp=function(){};
g.k.Cl=function(){return!1};
g.k.FD=function(){};
g.k.Dz=function(){};
g.k.Oq=function(){};
g.k.Nq=function(){};
g.k.KE=function(){};
g.k.Mr=function(){};g.v(b6,g.iS);b6.prototype.Pk=function(){return!1};
b6.prototype.load=function(){this.player.hideControls();this.j.show()};
b6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.hS("inline_preview",b6);})(_yt_player);
